from tkinter import *
w=Tk()
w.title("gui")
w.resizable(False,False)
w.geometry("600x400")
w.configure(bg="white")
l=Label(text="calculator")
l.grid(row=1,column=3)
l2=Label(text="Enter the first number")
l2.grid(row=2,column=1)
e = Entry()
e.grid(row=2,column=2,pady=5)
l3 = Label(text="Enter the second number")
l3.grid(row=3,column=2)
e2 = Entry()
e2.grid(row=3,column=3,pady=5)
e3=Entry()
e3.grid(row=5,column=2)
def add():
    r=(int(e.get())+int(e2.get()))
    e3.delete(0,END)
    e3.insert(END,r)
b=Button(text="+",command=add)
b.grid(row=4,column=2)
def sub():
    r=(int(e.get())-int(e2.get()))
    e3.delete(0,END)
    e3.insert(END,r)
b=Button(text="-",command=sub)
b.grid(row=4,column=3)
def mul():
    r=(int(e.get())*int(e2.get()))
    e3.delete(0,END)
    e3.insert(END,r)
b=Button(text="*",command=mul)
b.grid(row=4,column=4)
def div():
    r=(int(e.get())/int(e2.get()))
    e3.delete(0,END)
    e3.insert(END,r)
b=Button(text="/",command=div)
b.grid(row=4,column=5)
w.mainloop()
